### ISSUE TITLE
build produces ".main.js" but project uses "main.js"

### ISSUE THREAD

**Issue by batwicket** [chendesheng/ReagentNativeDemo#1]
The project.clj produces ".main.js" but the xcode project consumes "main.js". I notice because when i do a lein cljsbuild of the original source the two files do not match, perhaps because of versioning differences. I'm new to cljsbuild so I may be missing something.

**Comment by chendesheng** [comment]
This is intentional. Because I can't use the js generate by lein directly.
The main.js is works as a react native module (nodejs module) which also contains google closure module system itself. If you use .main.js directly you will see js errors. The reason of these js errors is because there is a variable named "goog", it must be global but it is not because main.js is inside a module. 

I made two changes to main.js.
1. Change "var goog = goog || {}" to "goog={};" this makes goog global and fix the js errors
2. Replace js code generated from core.cljs (on bottom of main.js) with require("./out/reagentnative/core.js"). Every time lein builds it generate core.js from core.cljs (like .o file before linking), this call to require core.js will concat main.js and core.js together.

Because I don't want to change main.js every time I build the project so I change output to .main.js

**Comment by batwicket** [comment]
Thanks, that answers my question. Perhaps this becomes the first ramp onto a freeway :).
